### PR TITLE
Fix broken spanwners recipe in ancient altar

### LINKED ISSUE #98: Ancient Auto Altar Spawners bug (SoulJars compatibility)
## Description (Required)
When trying to create a broken spawner from Auto Altar, there was a bug and the altar created some "custom" spawner and not the spawner listed in the Slimefun guide book. This means that this spawner cannot be repaired and a Reinformaced spawner created

## Steps to reproduce the Issue (Required)
Spawner must be crated & fixed in the Ancient Altar (multi-block)
https://www.youtube.com/watch?v=1R68ZRNPbSc

## Expected behavior (Required)
That will create the spawner listed in the slimefun guide (SoulJars)

## Environment (Required)
obrazek

 - Minecraft Version: Airplane 1.17.1
 - CS-CoreLib Version: none
 - Slimefun Version: 982
 - FluffyMachines Version: 90

### PR DESCRIPTION
**Pull request by ybw0014**
## Short Description

Fix the broken spawner recipe output using soul jars as catalyst. 
The `MOB_TYPE_BROKEN_SPAWNER` item are used to display the recipe only, the output is not the same as the displayed item, so I change the output, players can use them for crafting reinforced spawners.

## Additions/Changes/Removals

Change the recipe output for broken spawner.
I keep the old item, if the displayed broken spawner can be used for crafting reinforced spawners, this code snippet can be removed.

## Related Issues

Fix #98

## Video Proof

https://youtu.be/sIwa_7pcGqM

## Checklist

- [x] I have fully tested the proposed changes and promise that they will not break everything into chaos.
- [ ] I have tested every variant of every item or config setting that I have added.
- [x] I have also tested the proposed changes in combination with base Slimefun and made sure nothing breaks/unexpected happens.
- [ ] I followed the existing code standards and didn't mess up the formatting.
- [ ] I did my best to add documentation to any public classes or methods I added which may not be obvious to maintainers.
- [ ] I have added `Nonnull` and `Nullable` annotations to my methods to indicate their behaviour for null values

### CODE REVIEW

File: src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java [hunk 1]
```diff
@@ -335,14 +336,21 @@ private void craftIfValid(Block block, boolean craftOnce) {
         if (Constants.isSoulJarsInstalled && sfCatalyst != null
             && sfCatalyst.getId().startsWith("FILLED") && sfCatalyst.getId().endsWith("SOUL_JAR")) {
 
-            SlimefunItem spawnerItem = SlimefunItem.getById(sfCatalyst.getId().replace("FILLED_", "").replace(
-                "_SOUL_JAR", "_BROKEN_SPAWNER"));
+//            SlimefunItem spawnerItem = SlimefunItem.getById(sfCatalyst.getId().replace("FILLED_", "").replace(
```
Comment (NCBPFluffyBear) [inline src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java:339]: Old code can be deleted

File: src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java [hunk 2]
```diff
@@ -335,14 +336,21 @@ private void craftIfValid(Block block, boolean craftOnce) {
...
+//            "_SOUL_JAR", "_BROKEN_SPAWNER"));
+            EntityType entityType = EntityType.valueOf(sfCatalyst.getId()
```
Comment (NCBPFluffyBear) [inline src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java:341]: Add a null check to handle potential issues

**Review by NCBPFluffyBear — CHANGES_REQUESTED** [review]

File: src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java (hunk 2 above)
Comment (NCBPFluffyBear) [reply src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java]: I'd prefer if you did `if (entityType == null) { return; }` (Decreases number of indentations, more concise to me)

Comment (ybw0014) [reply src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java]: the `valueOf` method of enum will throw `IllegalArgumentException` if the given string is invalid, and will never be null, this is why I catch it.

**Review by NCBPFluffyBear — CHANGES_REQUESTED** [review]

File: src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java [hunk 3]
```diff
@@ -341,6 +341,8 @@ private void craftIfValid(Block block, boolean craftOnce) {
                         .replace("FILLED_", "")
                         .replace("_SOUL_JAR", ""));
 
+                if (entityType == EntityType.UNKNOWN) { return; }
```
Comment (NCBPFluffyBear) [inline src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java:344]: Please format into multiple lines

File: src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java [hunk 4]
```diff
@@ -341,6 +341,8 @@ private void craftIfValid(Block block, boolean craftOnce) {
                         .replace("FILLED_", "")
                         .replace("_SOUL_JAR", ""));
```
Comment (NCBPFluffyBear) [inline src/main/java/io/ncbpfluffybear/fluffymachines/machines/AutoAncientAltar.java:342]: Move `);` down to a new line

**Review by NCBPFluffyBear — CHANGES_REQUESTED** [review]

**Review by NCBPFluffyBear — APPROVED** [review]
